# Generated by Django 5.1.1 on 2024-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_variation_delete_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='variation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
