# Generated by Django 5.1.1 on 2024-09-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='average_price',
            new_name='minimum_price',
        ),
    ]
